plugins {
    id 'java'
}

group = 'com.nexign'
version = 'unspecified'

repositories {
    mavenCentral()
}

ext {
    springVersion = '3.4.3'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}