plugins {
    id 'java'
}

group = 'com.nexign'
version = 'unspecified'

repositories {
    mavenCentral()
}

ext {
    springVersion = '3.4.3'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation "org.springframework.boot:spring-boot-starter-amqp:${springVersion}"
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}

test {
    useJUnitPlatform()
}