server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/orders_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: message.direct

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


discount:
  service:
    url: http://localhost:8083