server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://172.22.22.58:5432/orders_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

discount:
  service:
    url: http://localhost:8082